language: node_js
node_js:
  - "3.3"
  - "5.6"
  - "8.11"
cache:
  directories:
    - "node_modules"
script:
  - "npm run test"
# Send coverage data to Coveralls
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"